services:
  db:
    platform: linux/x86_64
    image: postgres:14.1-alpine
    restart: on-failure
    container_name: 'brick-psql'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data/
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    networks: [ "brick" ]
  localstack:
    image: localstack/localstack:latest
    restart: on-failure
    container_name: 'brick-localstack'
    ports:
      - "0.0.0.0:4566:4566"            # LocalStack Gateway
      - "0.0.0.0:4510-4559:4510-4559"  # external services port range
#      - "0.0.0.0:53:53"                # DNS config (only required for MacPro)
#      - "0.0.0.0:53:53/udp"            # DNS config (only required for MacPro)
#      - "0.0.0.0:443:443"              # LocalStack HTTPS Gateway (only required for MacPro)
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-1
      - EDGE_PORT=4566
      - SERVICES=sqs
#      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
volumes:
  db:
    driver: local

networks:
  brick:
    driver: bridge